FROM nginx:alpine

# Copy halaman HTML langsung dari root folder
COPY index.html /usr/share/nginx/html/index.html

# Copy konfigurasi nginx langsung dari root folder
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

